In [10]:
import numpy as np

In [11]:
np.load("./conv_workspace/conv_in_f32.npz")['input.1']

array([[[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]]], dtype=float32)

In [12]:
np.load("./conv_workspace/conv_tpu_addressed_bm1684x_f32_weight.npz")['weight'].reshape(-1)

array([0., 1., 2., 3.], dtype=float32)

In [10]:
32-9

23

In [56]:
1 + 20 + 20 + (9  + 3 + 6 + 4 + 1)

64

In [72]:
res = bin((0xFFFFFFFFFFFFFFFF))
print(res[3:], len(res[2:]))

111111111111111111111111111111111111111111111111111111111111111 64


In [104]:
res = bin((0xFFFFFFFFFFFFFFFF - ((1 << 62) - 1) + ((1 << 42) - 1)))
print(res[3:], len(res[2:]))

100000000000000000000111111111111111111111111111111111111111111 64


In [109]:
bin(((0xFFFFFFFFFFFFFFFF - ((1 << 62) - 1) + ((1 << 42) - 1)) >> 42 ))

'0b1100000000000000000000'

In [100]:
cmd = (0xFFFFFFFFFFFFFFFF - ((1 << 62) - 1) + ((1 << 42) - 1))

In [114]:
bin((((0xFFFFFFFF - ((1 << 23) - 1)) + ((1 << 3) - 1))) >> 3)

'0b11111111100000000000000000000'

In [123]:
bin(0b1000100110)[2:].rjust(32,'0')

'00000000000000000000001000100110'

In [99]:
bin(cmd + (2<<42))

'0b1100000000000000000010111111111111111111111111111111111111111111'

In [81]:
res = bin((0xFFFFFFFFFFFFFFFF - ((1 << 42) - 1) + ((1 << 22) - 1)))
print(res[3:], len(res[2:]))

111111111111111111111000000000000000000001111111111111111111111 64


In [90]:
bin(((1 << 20) - 1))[2:]

'11111111111111111111'

In [91]:
len("11111111111111111111")

20

In [130]:
0b10000100110
0b01000100110

550

550

In [16]:
len('0000000000000000000')

19

In [14]:
np.load("./conv_workspace/conv_bm1684x_f32_model_outputs.npz")['2_Conv'].reshape(-1)

array([24., 30., 36., 48., 54., 60., 72., 78., 84.], dtype=float32)

module attributes {chip = "BM1684X", version = 2.2} {
  func.func @conv(%G8192: memref<1x3x5x5xf32, strides: [75, 25, 5, 1]>) -> (memref<1x2x3x3xf32, strides: [18, 9, 3, 1]>) ({
    ^bb0(%G8192: memref<1x3x5x5xf32, strides: [75, 25, 5, 1]>)    //  run_mode=TPU_STATIC
      %R0, %D1 = "dma.tensor"(%G0, %B0) {decompress = False} : (memref<1x2x27x1xf32, strides: [54, 27, 1, 1]>, none) -> (memref<1x2x27x1xf32, strides: [27, 27, 1, 1]>, none)
      %R0.128, %D2 = "dma.tensor"(%G4096, %B0) {decompress = False} : (memref<1x2x1x1xf32, strides: [2, 1, 1, 1]>, none) -> (memref<1x2x1x1xf32, strides: [1, 1, 1, 1]>, none)
      %R1, %D3 = "dma.tensor"(%G8192, %B0) {decompress = False} : (memref<1x3x5x5xf32, strides: [75, 25, 5, 1]>, none) -> (memref<1x3x5x5xf32, strides: [32, 32, 5, 1]>, none)
      %R3, %B1 = "conv.normal"(%R1, %R0, %R0.128, %C0.0, %D3) {kernel = [3, 3], stride = [1, 1], in_zero = [0, 0], ke_zero = [0, 0], kernel_rotate = False, pad_mode = 0, pad = [0, 0, 0, 0], res_add = False} :